[features]
seeds = false
[programs.localnet]
anchor_first = "AtGABXydX8hgbBeeRE46kLDDnPTuZtTd7Yi7HjwMRNSg"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "/home/test/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
